services:
  vrising:
    build:
      context: .
      args:
        UID: 1001
        GID: 1001
    environment:
      - GAME_PORT=27015
      - QUERY_PORT=27016
      - FALLBACK_PORT=27017
      - RCON_PORT=25575
      - DATA_PATH=/services/appdata/vrising
    image: vrising-docker
    user: vrising:vrising
    volumes:
      - steamcmd:/home/vrising/.wine/drive_c/SteamCmd
      - server:/home/vrising/.wine/drive_c/VRisingServer
      - ${DATA_PATH}:/home/vrising/.wine/drive_c/VRisingData
    ports:
      - ${GAME_PORT}:${GAME_PORT}/udp
      - ${QUERY_PORT}:${QUERY_PORT}/udp
      - ${FALLBACK_PORT}:${FALLBACK_PORT}/udp
      - ${RCON_PORT}:${RCON_PORT}
    restart: unless-stopped
volumes:
  steamcmd:
  server:
