services:
  vrising:
    build:
      tags:
        - vrising-server:local
      context: .
      args:
        UID: 1001
        GID: 1001
    image: vrising-server:local
    env_file: .env
    user: vrising:vrising
    volumes:
      - steamcmd:/home/vrising/.wine/drive_c/SteamCmd
      - server:/home/vrising/.wine/drive_c/VRisingServer
      - ${DATA_PATH:-"/appdata/vrising"}:/home/vrising/.wine/drive_c/VRisingData
    ports:
      - ${GAME_PORT}:${GAME_PORT}/udp
      - ${QUERY_PORT}:${QUERY_PORT}/udp
      - ${FALLBACK_PORT}:${FALLBACK_PORT}/udp
      - ${RCON_PORT}:${RCON_PORT}
    restart: unless-stopped
volumes:
  steamcmd:
  server:
