version: "3.9"
services:
  vrising:
    image: vrising-docker
    environment:
      VRISING_SERVER_NAME: My V Rising Docker Server
      VRISING_SAVE_NAME: world1
    volumes:
      - steamcmd:/home/vrising/.wine/drive_c/SteamCmd
      - vrising-data:/home/vrising/.wine/drive_c/VRisingData
      - vrising-server:/home/vrising/.wine/drive_c/VRisingServer
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
volumes:
  steamcmd:
  vrising-data:
  vrising-server:
